name: Deploy Docker Container on Push

on:
  push:
    branches:
      - main 

jobs:
  docker-compose:
    runs-on: self-hosted  # Sử dụng self-hosted runner
    environment: docker
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Build and push Docker image
        run: docker compose -f WebApplication2/docker-compose.yml up --build -d


